name: MPF-Python Package

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mpf-py/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mpf-py/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mpf-py
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest maturin

    - name: Build with Maturin
      run: |
        pip install .
        
    - name: Run tests
      run: |
        # Run Python tests
        pytest tests/ -v
